name: Run K6 load tests
on:
  push:
    branches:
      - "*"
      - "master"
jobs:
  test-create-operations:
    runs-on: ubuntu-latest
    env:
      SUMMARY_TREND: avg,max,med,min,p(95),p(90),p(15),p(5)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Install K6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
          echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Build project
        run: |
          npm install
          npm run build
          mkdir ./reports/source

      - name: Run 'Create crocodiles' load test
        run: k6 run --summary-trend-stats="${SUMMARY_TREND}" --summary-export=./reports/source/crocodiles_create.json dist/crocodiles.create.js

      - name: Generate HTML Reports
        if: always()
        run: |
          ls ./reports/source
          ls ./reports
          node ./reports/report.js
